"""empty message

Revision ID: ad08ea137913
Revises: ffdc0a98111c
Create Date: 2021-06-02 16:13:01.315986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad08ea137913'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('details', sa.String(length=500), nullable=False),
    sa.Column('where', sa.String(length=100), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('dayOfWeek', sa.String(length=100), nullable=False),
    sa.Column('startTime', sa.String(length=100), nullable=False),
    sa.Column('endTime', sa.String(length=100), nullable=False),
    sa.Column('timeOfDay', sa.String(length=100), nullable=False),
    sa.Column('maxPartySize', sa.Integer(), nullable=False),
    sa.Column('groupAdmin', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dayOfWeek'),
    sa.UniqueConstraint('details'),
    sa.UniqueConstraint('endTime'),
    sa.UniqueConstraint('module'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('startTime'),
    sa.UniqueConstraint('timeOfDay'),
    sa.UniqueConstraint('where')
    )
    op.add_column('users', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'group_id')
    op.drop_table('groups')
    # ### end Alembic commands ###
